version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/postgres
    volumes:
       - ~/db_data:/data/postgres
    restart: unless-stopped
  
  pgadmin:
    depends_on: 
      - postgres
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - ~/dbms_data:/root/.pgadmin
       - ${PWD}/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    restart: unless-stopped